name: CI pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  B2F:
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run integration_test.py
        run: ./tests/integration_test.py
      - name: Run smoke_test.py
        run: ./tests/smoke_test.py
      - name: Run unit_test.py
        run: ./tests/unit_test.py
      - name: Build Docker image from Dockerfile
        run: docker build -t weather-ml-app:ci-test
      - name: Create container
        run: docker run --rm weather-ml-app:ci-test python --version
      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password--stdin
      - name: Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:v1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/weather-ml-app:v1
